### ISSUE TITLE
On using a high-contrast-theme some default colors, like the selection are nearly unrecognizable

### ISSUE THREAD

**Issue by MartinL0815** [XhmikosR/notepad2-mod#127]
Hi,

this issue is more or less an issue for the original code, but eventually your more the one to help to fix it.

Since some time I need to work with a high-contrast theme, so to say with black background and yellow text and so on.

The color defaults in Notepad2 are a bit problematic, but the selection background color is the worst color, because it is nearly "black" and I can't see it really on the black background.

Is there any chance to fix some coloring, especially this coloring, in relation to the high-contrast colors?

Best regards,

Martin

**Comment by Phanx** [comment]
You can change the selection background color yourself:

View > Customize Schemes > Default Text > Selected Text (Colors)

However, you should also turn off View > Mark Occurrences; otherwise, when selecting a single word the selection will be overlaid by the "mark occurrences" color which has poor contrast and isn't customizable.  (#115 requests this)

**Comment by MartinL0815** [comment]
I already started to change, but it is not that easy for more than one scheme. I need to change more than one color, because the C++ and tcl/Tk schemes are more than suboptimal for dark/black high-contrast-mode.
It would be nice to let Nodepad2 switch to a dark scheming if a dark/black high-contrast-mode is active.

**Comment by Phanx** [comment]
You can speed things up a bit by opening Notepad2.ini (if you're doing this in Notepad2 make sure you turn OFF the Settings > Save Settings On Exit option first) and using search-and-replace to change all instances of, for example, blue to yellow. It's been a long time since I used (or even looked at) the default schemes, but I think they're pretty consistent (eg. strings in every scheme are set to the same color) so this should mostly work.

In the long run, there's probably little hope of getting the color scheme system changed in Notepad2 (either -mod or the original), but it probably wouldn't be too hard to write some kind of script to auto-convert, say, TextMate themes to the Notepad2.ini format, and then you could easily import a theme that works for you. I've thought about it a few times, but as I'm pretty happy with my current theme and rarely feel the urge to change it, I haven't really had any motivation to spend time on such a project...

**Comment by MartinL0815** [comment]
Thanks for the advice!

I'll see what I can do.

**Comment by svnpenn** [comment]
I was having a problem with this as well, in that the default "occurences" color
is almost identical to the "selected text" color. As a workaround I inverted the
"selected text" color like this:

    [Default Text]
    Selected Text (Colors) = fore:ffffff; back:000000

[Example](/svnpenn/dotfiles/blob/882c4c3/notepad2/notepad2.ini#L12-L14)
