### ISSUE TITLE
Notepad3

### ISSUE THREAD

**Issue by QWp6t** [XhmikosR/notepad2-mod#143]
It seems there's yet another Notepad2 fork. After taking a brief look at the sauce, it seems like it's just a rebadged version of notepad2-mod. Nevertheless, I figured I'd post about it here so we can see if anything interesting ever gets added to it.

https://rizonesoft.com/introducing-notepad3/

https://github.com/rizonesoft/Notepad3

**Comment by blackcrack** [comment]
humm, die klauen und halten sich nicht an die GPL !
humm, the steal and do not respect the GPL !

dirty bas*beeep*

why the hack do they are not working there with ?

best regards
Blacky

**Comment by QWp6t** [comment]
Neither Notepad2 nor notepad2-mod are released under GPL. [The license](https://github.com/XhmikosR/notepad2-mod/blob/master/License.txt) is similar to [MIT](https://tldrlegal.com/license/mit-license#fulltext).

**Comment by blackcrack** [comment]
oh, then i have something not understand, but how ever..
why not working together.. ?

thank you for the info QWp6t :) :+1: 
best regards
Blacky

**Comment by rizonesoft** [comment]
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

**Comment by rizonesoft** [comment]
the same can be said about Notepad2-mod. Maybe the Notepad2-mod developers should have worked with the Notepad2 developer and not just create their own version. 

Notepad3 changes from Notepad2-mod:
- New toolbar icons and layout.
- New icons and some cosmetic changes.
- Sorted out the Duplicate pinned Taskbar icon issue.
- Added minipath.exe (metapath) plugin.
- Added Favorites folder.
- More coming soon!

**Comment by blackcrack** [comment]
so, why not easy working together , and have a standard and together an better bug fixing and so on ? An common Forum maybe.. the space therefore exist :) how i see ..

maybe with the possibility for themeing.. icons and so on.. as snapin for toolbar and icons for fs in window like it works in bandizip.. how ever, only so an idea.. 
themeiconpack.notefstheme / toolbarisontheme.notetoolb  (maybe boot zipfiles with png's)
as suggestion.

well.. it's a good thing, like i can read ..
(btw, make not too much external things, the single exe mus able to change out the notepad from Windows or maybe reactos.org, if you know it  ;) )

best regards
Blacky

**Comment by QWp6t** [comment]
@rizonesoft Upstream Notepad2 maintainer (Florian Balmer) is not interested in including the added features from Notepad2-mod and other forks. But I know that Kai Lui and myself have both submitted patches to him, and I believe @XhmikosR has at least been in communication with him.

@blackcrack The primary distinction here is that Notepad3 appears to be under active development while Notepad2-mod should be considered to be in maintenance mode. Notepad2-mod is very selective about which features are added and which PRs are accepted because at the moment this repo is maintained solely by @XhmikosR, and if upstream is ever updated, it would likely fall on him to patch in all of the modifications.

**Comment by XhmikosR** [comment]
@QWp6t is correct.

Some notes.

Back in 2009 I was using Kai Liu's fork. Then he stopped updating it so I contacted the Notepad2 author to see if he would merge the patches. He wasn't interested at the time, so I decided to see if I could patch things up myself. That is the reason for this fork. But yeah, I always contacted the people before me.

I don't have any time to maintain this for a long time now. But generally I try to keep an eye on Notepad2 since it's my main editor. I only miss tabs, otherwise I wouldn't use any other editor at all.

That being said, the beauty or curse of open source is this one exactly. Forks of forks of forks instead of collaborating with the others (or even just contacting them).

**Comment by blackcrack** [comment]
i know Flo too, he's a german like me :)
it's good to speak together :) and not over the other one :)

btw, i love notepad2 and i like to be other interested on it..
notepad2 it's the notepad where i have replaced and programming in php
like that : http://www.blackysgate.net/phpfilemirror/
in openmandriva i use kwrite, but in WinNT like Reactos.org and MS WinNT i use notepad2-mod

best regards
Blacky

**Comment by rizonesoft** [comment]
@QWp6t I just wanted to implement my own patches and updates. I created Notepad3 because I wanted it not to be just another fork, but an upgraded and actively developed version derived from the Notepad2 projects. That is the good side of open source. Projects live forever! I give credit where need be and will always be fair towards other developers. I was not trying to step on any toes or upset anybody. Just trying to do my own thing my own way. IF that is acceptable?

**Comment by rizonesoft** [comment]
@blackcrack As mentioned to @QWp6t I was just trying to make something that stands out from the hundreds of Notepad2 forks and the best way to do this is by changing the name. Do a search for Notepad2 versions and you will find many forks. I just want to bring everything together into an updated rounded version.

**Comment by QWp6t** [comment]
@rizonesoft To be clear, I started this discussion with the idea that we could review your code and see if there's anything that we should be poaching from it. I never thought you were being unfair to any developers or stepping on anyone's toes or anything like that. :+1: 

My opening sentence in this issue is, "It seems there's yet another Notepad2 fork." I think that encompasses how I feel about your project: I never thought negatively of it, my feelings about it are rather benign. I view it as another code pool to draw from so we can all make better open sauce. :tomato: 

Happy coding everyone! :smiley:

**Comment by rizonesoft** [comment]
@QWp6t Thanks! Happy coding.. Poach away. Just hope I can add some value to the code pool.

**Comment by joedf** [comment]
Genetic code pool... Hehehe :troll:

**Comment by blackcrack** [comment]
@rizonesoft
@QWp6t 
@XhmikosR 

:+1:  :)
best regards
Blacky

p.s.: @joedf this is like make baby's in the labor ;) 
maybe it's  give a in future a ultima-prime notepad2-4.0 die hard  ..hehe

**Comment by rizonesoft** [comment]
@blackcrack. Thats actually not a bad idea. A forum to bring it all together. I will create a coding forum with sections dedicated to certain projects. One dedicated to Notepad2?

**Comment by blackcrack** [comment]
! well idea ! maybe a Notepad2 "forever" or just "4.0 die hard" ;) *giggle*
in any case, you direct with the name and do and draw up an way for the doo in future
and can be therewith a target in the future far, far ... in the future ;) bit it is not a fairy tale, it's a possible where you can draw, the Founder of Notepad2, Florian, can maby once day come backt to some project, because he was the founder (in all honor) and can maybe resume one's seat, if he want, and there should be the name fit still or want be an totally other project.. maybe can you he invite in a couples of years and he is then still the silence chef again ;) Because, imho be the whole forks be the child's of notepad2 .. in any case and why should the child's not support the "Dad" and the Founder of this Project, therewith can we.. you are say thank you .. for this nice founding .. and can common working in one direction.. to make notpad2 to something common unique and
matchless .. better as the [baeh]n++[/baeh] (i don't like it because have to much files ..) 
what it is even/already now ..

so, Notepad2 forever (die Hard 4.0) :smile_cat: ears and extensions  ;)

best regards
Blacky
