### ISSUE TITLE
the toolbar icons are too small on high dpi screens!

### ISSUE THREAD

**Issue by neatgz** [XhmikosR/notepad2-mod#209]
windows 10,  400% DPI
the toolbar icons are too small, hard to recognize, hard to hit.
cannot find anywhere to customize the size of the toolbar icons.
will an upgrade appears to solve it?
thanks.

**Comment by blackcrack** [comment]
then should you not use a UHD TV with the highest resolution
or not Win10 who make it maybe not right scaled..
400 percent of normal 100% / 96ppi make this sure an bit crazy..
It's maybe not bad to add a size regulation of 1 000 percent of the icons \*hrchhrchhrch*

**Comment by neatgz** [comment]
@blackcrack 
I know that 400% DPI was a little crazy. But I am using DELL UltraSharp UP3218K . No choice except win10, No choice except 400% DPI.
As a matter of fact, high dpi screens is becoming more and more popular. Surface pro, dell xps, macbook pro (with win10) and so on. Their dpi are all about 150% ~ 300% . 
I just tested notepad2-mod on my macbook pro (win10 , system default 200% DPI) . the toolbar icons are also too small. 
So, I think, the point is NOT 400% DPI or 1000% DPI, the point is it's time to be adapted to the high dpi screens.
If possible and If the workload is large, maybe the author can only have the icons enlarged on high dpi screens , instead of keep the clarity of the icons , so Users can hit it easily.
Besides, I guess Microsoft may have already provide some API for the high dpi screens ? 
Best Regards
and thanks

**Comment by blackcrack** [comment]
\*rofl*
oohh booy.... 
and you meant seriously it's a issue for notepad ?
you make the task to other peoples.. or better explain, your problem to other problems,
you have build together this hardware like it is and not notepad-mod or other else..
so the program runs very well and it's very nice like it is, but this is no support-forum or something where you pay for it, and therewith also not a fitting for specially your problems/ or maybe a task for other who not become money for it.. so, this is not a issue for notepad-mod, this is 

"i have build it together, i have live with it"
me/i have a 42" Monitor with HD resolution with 1920x1080 and all works very fine
so, no need for "Supporting you"  would very nice if you change the status of your issue as resolved, because, this is not a notepad-mod issue, this is a scaling issue of Microsoft WinNT10  
and not by the notepad-mod..

good slip in the new Year and have a nice new Year

best regards
Blacky

you can remove this issue by the button "Close the issue" bottom edge with the Button ;)

**Comment by neatgz** [comment]
I do not know wether compatibility (or display) problem is an issue or not. 
I will not close it until the author told me, but not you. 
Actualy, I think, bugs, suggestiones and so on, they all can be an issue.
I know clearly that the author has no obligation to deal with this problem. 
But I think, Feedback suggestiones or problems in the open source community is a good thing.
So I only post an compatibility problem on high dpi screens and provide some suggestions , What to do next depends on the author , this is .  and I did NEVER asked the author must to solve it. 
I know clearly The feedback does not mean after-sales service , You forcibly misinterpreted me.(maybe because English is not my mother language , so some of the previous sentences and tone may be differ from my original intention.)
Since you mentioned the money thing, then I will do it if notepad-mod works well and the author accepts donations.
besides, this problem is NOT my own, it appears on all high dpi sceens.
one more thing, many program displays well on high dpi screens such as notepad++ , and some not . I don not know this is a notepad-mod issue or a microsoft issue. Maybe microsoft issue , whatever.
best regards.

**Comment by blackcrack** [comment]
what ever, it is pointed out .

best regards
Blacky

**Comment by neatgz** [comment]
the problem was solved :
right click on the notepad-mod.exe
Click on the properties menu item and select the compatibility tab.
Select "Disable display scaling on high DPI settings". and try the three options , one of them will make notepad2-mod works well on high DPI screens.
