### ISSUE TITLE
Block select (Alt-mouse-drag) causes AV

### ISSUE THREAD

**Issue by mcbotha** [XhmikosR/notepad2-mod#37]
When trying to select a block with Alt-mouse-drag causes the application to fall over on Windows 8.

**Comment by craigo-** [comment]
Hi -

I have experienced this bug for many versions of Notepad2-mod now... but it seems to only affect the x64 build.

Attached: [test.zip](https://github.com/XhmikosR/notepad2-mod/files/203788/test.zip) containing the file test.vbs that I can reliably use to reproduce the problem.

Version used: Notepad2-mod (64 bit) 4.2.25 r972 (68b1190)
Platform: Windows 7 Professional, 64-bit

Steps to reproduce:

1.  Open the attached file
2.  Scroll so lines 31-37 are visible
3.  While holding down alt, click and hold on line 32 between characters  3 & 4 (the start of the word "IsMember") and move the mouse pointer in circles around the starting point

Result:
![capture](https://cloud.githubusercontent.com/assets/4467963/14270681/93862116-fb44-11e5-901a-9b702ad3c435.PNG)

Doing this, I can get Notepad2-mod to crash 75-90% of the time. Not always. It appears if I keep retrying, the crash becomes less likely to occur. It becomes more likely after restarting.

Note that I can get it to crash while trying to alt-select other parts of the file. (I first thought the code folding feature might be responsible, but it can crash when selecting text that is not considered foldable.)

I have tried the same using a vanilla notepad2.ini file but can still reproduce the crash.

I have tried the same using Notepad2-mod (x86) 4.2.25 r972 (68b1190) and do not experience the crash.

I have tried the same using Notepad2 4.2.25 (x64) from flos-freeware.ch and do not experience the crash.

I may be wrong, but it sounds to me like the bug is coming from one of three sources:

- the Notepad2-mod code
- the 64-bit compile process
- a version of Scintilla in Notepad2-mod that is not in Notepad2

I am continuing to test to see if I can further narrow down the problem.

**Comment by oezgueremir** [comment]
Hi!

I think this could be the bug in Scintilla I traced back some time ago
in 2013.
I never could do a bug fix, nor did I forward my report, shame on me.

Well, if I remember well, the problem is, that all procedures are
message based and therefore not real time procedures.
So, when you are selecting some text, the code sequence has somthing
like this in it:
- sendmessage(get_selection_length)
- allocate new textbuffer in size of selection_length
- sendmessage(copy get_selected_text to textbuffer)
(sorry for that extreme pseudo code)

Back to the Bug. It is much easier to provoke than you think.
For instance, let's talk about Line 31:
If IsMember("Group B") = True Or _

Just select "IsMembe" (without the "r").
Now with one swift and fast move select the remaining line.
It is important, that you stay in one single Line.
The Editor should now crash.

This is what happens.
While you select more characters, the intermediate answer of
get_selection_length is for instance 8 ("IsMember"). Scintilla allocates
a buffer for 8 characters.
But when it comes to "copy get_selected_text to textbuffer" your
selection is 31 ("IsMember("Group B") = True Or _"). This leads to a
clear buffer overflow.
Sometimes notepad dodges it, sometime it crashes...


If I should find the right code area, I will hopefully provide more
detailed information...

Regards



Am 05.04.2016 um 06:12 schrieb craigo-:

**Comment by oezgueremir** [comment]
Now I think harder about it, I had a bugfix concept.
I did forward the previous get_selection_length as "max_length" via the wParam for the get_selected_text message. That worked good, but still, I didn't send a DIFF or pull request...
I think there was an issue for using the wParam.

I really have to dig my working environment and find my patch...

**Comment by craigo-** [comment]
This sounds rather promising, @oezgueremir. If we could work around the problem within notepad2-mod's code, then that sounds good... But wondering where the actual problem is originating. Should we be reporting this upstream to the Scintilla devs? Do you think this is something they could/should address?

In your experience, have you ever seen this bug using notepad2-mod x86?

**Comment by craigo-** [comment]
I can confirm that this problem still exists when using notepad2-mod 4.2.25.980 (x64 build) on Windows 7 Pro x64.

**Comment by RaPeHoff** [comment]
Reproducing this issue with attached debugger throws an exception:

"Run-Time Check Failure #1 - A cast to a smaller data type has caused a
loss of data.
 If this was intentional, you should mask the source of the cast with the
appropriate bitmask.
 For example:
char c = (i & 0xFF);
Changing the code in this way will not affect the quality of the resulting
optimized code."
in Scintilla's PlatWin.cxx method SurfaceGDI::AlphaRectangle() calling
dwordFromBGRA()

A workaround this would be compiling release version without run-time check
for typecast to smaller type (/RTCc).
Other Solution - Fixing it in the methode above (PlatWin.cxx method
SurfaceGDI::AlphaRectangle()):
Maybe:
      ...
      DWORD valFill = dwordFromBGRA(
        LOBYTE(fill.GetBlue() * alphaFill / 255),
        LOBYTE(fill.GetGreen() * alphaFill / 255),
        LOBYTE(fill.GetRed() * alphaFill / 255),
        LOBYTE(alphaFill));

      DWORD valOutline = dwordFromBGRA(
        LOBYTE(outline.GetBlue() * alphaFill / 255),
        LOBYTE(outline.GetGreen() * alphaFill / 255),
        LOBYTE(outline.GetRed() * alphaFill / 255),
        LOBYTE(alphaOutline));
...
(Rem.: LOBYTE macro from <minwindef.h>  #define LOBYTE(w) ((BYTE)(((
DWORD_PTR)(w)) & 0xff))


2016-06-07 3:11 GMT+02:00 craigo- <notifications@github.com>:

**Comment by XhmikosR** [comment]
Or, you could let the Scintilla developer know about the issue. Just saying.

**Comment by RaPeHoff** [comment]
Ok, Scintilla Bug-Tracker #1838.

2016-06-07 10:44 GMT+02:00 XhmikosR <notifications@github.com>:

**Comment by XhmikosR** [comment]
@RaPeHoff: thanks, I will follow that ticket.

**Comment by craigo-** [comment]
Just bringing to your attention that the abovementioned Scintilla bug report has been closed as "wontfix". there is a bit of dialogue as to why...

https://sourceforge.net/p/scintilla/bugs/1838/

**Comment by RaPeHoff** [comment]
... Yes, this issue is not the reason for the "crash" which was reported
before.
Except, if you compile the application with option /RTCc (run-time checks
for casts) - if you don't use this option, you will have no problem here
(even if this piece of code violates some basic programming guidelines).
The reported problem seems to be related to a buffer-overflow, caused by a
trailing '\0' in a text-buffer which is too small for this.
Unfortunately I have no time at the moment to debug into this ...

Regards,
Rainer


2016-09-06 4:11 GMT+02:00 craigo- <notifications@github.com>:

**Comment by XhmikosR** [comment]
The buffer overflow is in Scintilla or in our code?

**Comment by CoolCmd** [comment]
confirmed. notepad2-mod x64 4.2.25 r985 (and early versions), windows 7.
after block select (alt+shift or alt+click) notepad crash, sometimes immediately, sometimes before exit.
original notepad2 never crashed.
this bug very old and therefore i never use notepad2-mod.

**Comment by RaPeHoff** [comment]
The related answer from Neil Hodgson:
" ...
The original notepad2 crash is more likely to be that the call made to
Scintilla to get the selection (possibly SCI_GETSELTEXT) adds a NUL (0)
byte to the end of the buffer so it requires 1 more byte than the selection
length.
..."
implies, that it must be the code which uses the Scintilla library, so it
is the notepad2 code.

Regards,
Rainer




2016-09-06 10:42 GMT+02:00 XhmikosR <notifications@github.com>:

**Comment by XhmikosR** [comment]
I do see numerous related issues in Coverity but I don't have time to try and fix them.

If anyone wants request access to Coverity and submit a PR to fix them.

**Comment by craigo-** [comment]
Hi, @XhmikosR -

I have tested rizonesoft/Notepad3 (build 392) on Windows 7 x64, and this issue appears to be fixed in that codebase. Is that enough evidence for you to incorporate the same fix into this project?

**Comment by XhmikosR** [comment]
If you make a PR with that fix only and a link to the upstream patch, I could have a look.

**Comment by craigo-** [comment]
I'd love to, but try as I may, I'm not yet proficient enough in C, Git or GitHub to assist. I'm sure one of you lot out there is.

**Comment by RaPeHoff** [comment]
the PR (#178) exists already since Nov 17, 2016
<https://github.com/XhmikosR/notepad2-mod/pull/178#issue-189981703>


2017-01-26 23:27 GMT+01:00 craigo- <notifications@github.com>:

**Comment by XhmikosR** [comment]
@RaPeHoff: yes but I don't see any info that this is the same patch as there. And if so, who's the author, attribution etc.

**Comment by RaPeHoff** [comment]
the author is me (in both cases: PR #178 and Notepad3 fix), the difference
is: Notepad3 has interwined more fixes and features
and i had no time to learn Git deeply enough to supply attribution or
branch linkages between different forks (notepad2-mod, Notepad3).

2017-01-27 8:59 GMT+01:00 XhmikosR <notifications@github.com>:

**Comment by XhmikosR** [comment]
I don't follow other forks hence my question.

Is the patch the exact same one?

**Comment by RaPeHoff** [comment]
... i checked again - yes, PR #178 is exactly the patch, which has been
applied to Notepad3 regarding this issue (notepad2-mod #37).

2017-01-27 9:32 GMT+01:00 XhmikosR <notifications@github.com>:

**Comment by zufuliu** [comment]
only need to change two line in EditMarkAll()

**Comment by XhmikosR** [comment]
To whoever has this crash, can you try the patch from #182?

**Comment by craigo-** [comment]
I don't currently have a dev setup. I can test binaries...

**Comment by zufuliu** [comment]
Hi @craigo- can you try the build from https://github.com/zufuliu/notepad2/releases?

**Comment by szepeviktor** [comment]
@zufuliu It is merged.

**Comment by craigo-** [comment]
@zufuliu, I can test... Within the next 48 hours.

**Comment by blackcrack** [comment]
https://github.com/XhmikosR/notepad2-mod/issues/199

**Comment by craigo-** [comment]
@zufuliu, I have just tested your x64 build v2.4.5b1028 (internally listed as version 4.2.25 r1028) from [github.com/zufuliu/notepad2/releases](https://github.com/zufuliu/notepad2/releases)... It does not exhibit this problem.

At the same time, I tested the latest x64 build (4.2.25.995) from @XhmikosR, and it does still crash as previously described. Looking forward to a new binary release :)

**Comment by zufuliu** [comment]
@craigo- PR #182 is just merged, it will available in a later release.

**Comment by XhmikosR** [comment]
I'll release a new stable soon. I need to find time to make the changes for VS2017.
